// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuwfllutcznyygbxkegu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1d2ZsbHV0Y3pueXlnYnhrZWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDIyNTUsImV4cCI6MjA2NDYxODI1NX0.uBFyJwIf6V_50XiOhMkkFDu6ArZKHhc1PkOXMokF-Qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);